// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Articles',
      link: { type: 'doc', id: 'articles/index' }, 
      items: [
        {
          type: 'category',
          label: 'Custom Item',
          link: { type: 'doc', id: 'articles/custom-item/index' },
          items: [{ type: 'autogenerated', dirName: 'articles/custom-item' }],
        },
        {
          type: 'category',
          label: 'Custom Role',
          link: { type: 'doc', id: 'articles/custom-role/index' },
          items: [{ type: 'autogenerated', dirName: 'articles/custom-role' }],
        },
        {
          type: 'category',
          label: 'Global Event',
          link: { type: 'doc', id: 'articles/global-event/index' },
          items: [{ type: 'autogenerated', dirName: 'articles/global-event' }],
        },
      ],
    },
  ],
};

export default sidebars;


